blank_issues_enabled: true
contact_links:
  - name: Nightosphere Support
    url: https://t.me/NightoXchat
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://t.me/NightosphereVIP
    about: Documentation for getting started with bot.
